### ISSUE TITLE
How to run one step adaptive inference or two step adaptive inference?

### ISSUE THREAD

**Issue by EsamiLDR** [ChicagoHAI/hypothesis-generation#13]
As I questioned in the title, I've tried default, filter and weight, upperbound inference, and they all worked well. 
But I can't ran one step adaptive inference or two step adaptive inference just by change the inference parameter "--inference_style". Each time I ran it, the function "_fill_multi_content" in the "prompt.py" document always went wrong. 
Is there any other parameters or code I need to change? I would sincerely appreciate your help!

**Comment by laoliu5280** [comment]
Hi, thank you for submitting the issue. I have fully investigated the issue, and it turns out there's a bug with the prompt class for the two adaptive inference methods. We recently changed the way we handle nested prompts, and we apologize for not realizing this issue sooner.

I have made hot fixes to both the master branch of this repository and the datasets' repository (I had to change the prompt template for `adaptive_info_prompt`). Please update both repositories and see if it works.

We are undergoing some major updates recently. We are introducing some upgrades to the current framework that adds literature to the hypothesis generation pipeline and many more code optimizations. Stay tuned!
